services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=multiservices
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  database:
    build: ./database
    ports:
      - "8009:8080"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  order-service:
    build: ./order-service
    ports:
      - "8000:8080"
    volumes:
      - ./order-service/src:/app/src
      - ./order-service/build.gradle:/app/build.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  inventory-service:
    build: ./inventory-service
    ports:
      - "8001:8080"
    volumes:
      - ./inventory-service/src:/app/src
      - ./inventory-service/build.gradle:/app/build.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

volumes:
  postgres-data:
