services:

# infrastructure
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=multiservices
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  database:
    build: ./database
    ports:
      - "8009:8080"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"


# services

  user-service:
    build: ./user-service
    ports:
      - "8000:8080"
    volumes:
      - ./user-service/src:/app/src
      - ./user-service/build.gradle:/app/build.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    #      - JWT_SECRET_KEY=ENV=ZGVmYXVsdFNlY3JldEtleVRoYXRTaG91bGRCZU92ZXJyaWRkZW5JblByb2R1Y3Rpb24=
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  order-service:
    build: ./order-service
    ports:
      - "8001:8081"
    volumes:
      - ./order-service/src:/app/src
      - ./order-service/build.gradle:/app/build.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    #      - JWT_SECRET_KEY=ENV=ZGVmYXVsdFNlY3JldEtleVRoYXRTaG91bGRCZU92ZXJyaWRkZW5JblByb2R1Y3Rpb24=
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  inventory-service:
    build: ./inventory-service
    ports:
      - "8002:8082"
    volumes:
      - ./inventory-service/src:/app/src
      - ./inventory-service/build.gradle:/app/build.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  reservation-service:
    build: ./reservation-service
    ports:
      - "8003:8080"
    volumes:
      - ./reservation-service/src:/app/src
      - ./reservation-service/build.gradle:/app/build.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  payment-service:
    build: ./payment-service
    ports:
      - "8004:8080"
    volumes:
      - ./payment-service/src:/app/src
      - ./payment-service/build.gradle:/app/build.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

volumes:
  postgres-data:
